program: image_decode_search.py
method: bayes
metric:
  goal: maximize
  name: average_image_predict_success
parameters:
  layer_sizes:
    values: [[10, 10, 10, 10, 10], [20, 20, 20, 20, 20], [30, 30, 30, 30, 30], [40, 40, 40, 40, 40], [50, 50, 50, 50, 50], [60, 60, 60, 60, 60], [70, 70, 70, 70, 70], [80, 80, 80, 80, 80], [90, 90, 90, 90, 90], [100, 100, 100, 100, 100]]
  learning_rate:
    min: 0.000001
    max: 0.01
  dt:
    values: [0.01]
  percentage_inhibitory:
    min: 10
    max: 30
  exc_to_inhib_conn_c:
    min: 0
    max: 1
  exc_to_inhib_conn_sigma_squared:
    min: 1
    max: 60
  tau_mean:
    min: 120
    max: 3000
  tau_var:
    min: 4
    max: 100
  tau_stdp:
    min: 0.004
    max: 0.1
  tau_rise_alpha:
    min: 0.0004
    max: 0.01
  tau_fall_alpha:
    min: 0.002
    max: 0.05
  tau_rise_epsilon:
    min: 0.001
    max: 0.025
  tau_fall_epsilon:
    min: 0.004
    max: 0.1
  decay_beta:
    values: [0.8]
  threshold_scale:
    values: [1.1]
  threshold_decay:
    values: [.985]
